[devices.ram0]
type = "memory"
is_rom = false
size = "0x4000"

[devices.rom0]
type = "memory"
is_rom = true
size = "0x8000"
load = "apps/pixel/pixel.bin"

[devices.acia0]
type = "acia"

[devices.display0]
type = "display"

[chips.cpu0]
type = "65C02"

[links.cpu0.bus]
ram0 = "0x0000"
rom0 = "0x8000"
acia0 = "0x5000"
display0 = "0x5010"

[links.acia0]
irq = ["cpu0"]
